### ISSUE TITLE
Mod violates mod security

### ISSUE THREAD

**Issue by Wuzzy2** [edu-minetest/quiz#3]
When I start the mod and try to answer the dummy question (hit OK), the server shuts down with this message:

```
AsyncErr: Lua: Runtime error from mod 'formspecs' in callback on_playerReceiveFields(): Mod security: Blocked attempted write to ~/.minetest/mod_data/quiz/students/singleplayer
stack traceback:
	[C]: in function 'mkdir'
	~/.minetest/mods/quiz/init.lua:129: in function 'logQuiz'
	~/.minetest/mods/quiz/quizzes.lua:244: in function 'check'
	~/.minetest/mods/quiz/init.lua:328: in function 'checkAnswer'
	~/.minetest/mods/quiz/init.lua:402: in function 'on_close'
	~/.minetest/mods/formspecs/init.lua:143: in function <~/.minetest/mods/formspecs/init.lua:128>
	/usr/share/minetest/builtin/game/register.lua:446: in function </usr/share/minetest/builtin/game/register.lua:432>
```

Yeah, sorry but writing directly into my `.minetest` directory is 1) rude and 2) not good development practice. To store data, Minetest has better functionality anyway (like mod storage). So please use that instead of attempting to pollute my diretories.

**Comment by snowyu** [comment]
What's the MT version you used?

It should not happend if your MT have not merged the `mod_data` PR.  It stores the data to world directory instead. 
stores into the mod folder is not a good idea for it will be overwrite after upgrading.

**Comment by Wuzzy2** [comment]
5.7.0

**Comment by snowyu** [comment]
fixed for RUN_IN_PLACE=0
